"""
Characterise the `motion_difficulty` axis of TDMovingMNISTDataset.

`motion_difficulty=d` controls HOW OFTEN the velocity changes and nothing else:
jump size is pinned at the training value (smooth_probability=0.80) and
max_speed is untouched. Paired with neighbor_kernel="symmetric" the stationary
velocity distribution is uniform at every d, so mean |v| does not drift and
difficulty is not confounded with speed.

d = 0.5 IS the training regime, which gives the sweep a reference point.

Run directly to print the table for the paper appendix:

    python moving_mnist/tests/test_motion_difficulty.py
"""
import math
import os
import sys
from pathlib import Path

import numpy as np

_HERE = Path(__file__).resolve().parent
_PKG = _HERE.parent
if str(_PKG) not in sys.path:
    sys.path.insert(0, str(_PKG))

from time_dependent_moving_mnist_dataset import TDMovingMNISTDataset  # noqa: E402

DATA_ROOT = os.environ.get("MNIST_ROOT", str(_PKG / "data"))

D_GRID = (0.0, 0.2, 0.35, 0.5, 0.65, 0.8, 1.0)
N_TRAJ = int(os.environ.get("N_TRAJ", 20000))
SEQ_LEN = 100
MAX_SPEED = 2
NUM_DIGITS = 2
FREEZE = 15
SEED = 20240521
KERNEL = "symmetric"

# _apply_freeze propagates motions[f-2] = motions[13] through the whole rollout,
# so the context steps are motions[0 .. 13] and the boundary age is the number of
# frames motions[13] had been held. A trajectory that never changes counts its
# initial draw at index 0, giving the maximum age 14.
N_CTX_STEPS = FREEZE - 1          # 14 velocity steps inside the context
LAST_FREE_T = FREEZE - 2          # last free transition index, 13

# Uniform over velocity_grid: mean Euclidean speed. The symmetric kernel is
# doubly stochastic, so the sweep should sit on this value at every d.
UNIFORM_MEAN_SPEED = 1.9525

# Simulated regression targets.
#         p_change  H bits  mean|v|  net disp  switches  bnd age  E|dv|
EXPECTED = {
    0.00: (0.000, 0.000, 1.958, 27.41, 0.00, 14.00, 0.00),
    # switches at d=0.20 is 0.293, not the 0.28 of the task spec. Measured at
    # n=20000 over four independent seeds (0.2959/0.2908/0.2920/0.2921, mean
    # 0.2927 +/- 0.0022) and internally consistent with the realised rate
    # (13 * 0.0225 = 0.292). This is the rarest-event cell and so the noisiest
    # to simulate; every other entry in the table matches within 1%.
    0.20: (0.030, 0.231, 1.955, 26.74, 0.293, 12.19, 1.39),
    0.35: (0.102, 0.648, 1.952, 25.30, 0.99, 8.82, 1.38),
    0.50: (0.222, 1.218, 1.956, 23.25, 2.12, 5.70, 1.39),
    0.65: (0.393, 1.877, 1.952, 20.65, 3.76, 3.53, 1.39),
    0.80: (0.616, 2.574, 1.956, 18.19, 5.87, 2.29, 1.39),
    1.00: (1.000, 3.361, 1.953, 14.98, 9.54, 1.42, 1.39),
}
FIELDS = ("p_change", "entropy", "mean_speed", "net_disp", "switches",
          "mean_age", "mean_dv")

# Trajectories generated by the DEFAULT ("legacy") kernel, captured before the
# symmetric kernel was added. These must never move: existing fixed benchmarks
# depend on the legacy stream byte-for-byte.
LEGACY_TRAJECTORY_SHA256 = {
    "piecewise_smooth08":  "1ecd89a0d0b7eb8fe2beab55b2593244e778c4c5fd82cadd8b43758cb70a1c0d",
    "stochastic_smooth08": "7be06bab20335280477f6811d6d7be9c27788711477acc607a17958b815ba11b",
    "stochastic_smooth10": "97a8addd1cec02ec9558bf0ab5669b3108ab7fa0f99af05c3f42142395420b9a",
}

_CACHE = {}


def _dataset(d, **over):
    kw = dict(
        root=DATA_ROOT, train=False, seq_len=SEQ_LEN, num_digits=NUM_DIGITS,
        image_size=36, max_speed=MAX_SPEED, motion_difficulty=d,
        neighbor_kernel=KERNEL, freeze_after=FREEZE, download=False,
        random=False, seed=SEED, return_motion=True,
    )
    kw.update(over)
    return TDMovingMNISTDataset(**kw)


def _entropy_from_joint(joint):
    """H(v_t | v_{t-1}) in bits."""
    row = joint.sum(axis=1)
    total = row.sum()
    if not total:
        return 0.0
    h = 0.0
    for k in np.flatnonzero(row):
        p = joint[k][joint[k] > 0] / row[k]
        h += (row[k] / total) * float(-(p * np.log2(p)).sum())
    return h


def measure(d, n_traj=N_TRAJ):
    """Velocity-process statistics over the context steps motions[0 .. 13]."""
    if (d, n_traj) in _CACHE:
        return _CACHE[(d, n_traj)]

    ds = _dataset(d)
    ds.reset_rng()
    ctx = np.empty((n_traj, N_CTX_STEPS, NUM_DIGITS, 2), dtype=np.int16)
    for i in range(n_traj):
        ctx[i] = ds._generate_motion_trajectory().numpy()[:N_CTX_STEPS]

    v = ctx.astype(np.int64)
    changed = (v[:, 1:] != v[:, :-1]).any(axis=-1)              # (n, 13, D)
    switches = changed.sum(axis=1)                               # (n, D)

    idx = np.arange(1, N_CTX_STEPS).reshape(1, -1, 1)
    t_last = np.where(changed, idx, 0).max(axis=1)               # (n, D)
    ages = (LAST_FREE_T - t_last) + 1

    dv = np.abs(v[:, 1:] - v[:, :-1]).max(axis=-1)               # L-inf, (n,13,D)
    speed = np.sqrt((v ** 2).sum(axis=-1))                       # L2, (n,14,D)
    net = np.sqrt((v.sum(axis=1) ** 2).sum(axis=-1))             # (n, D)

    code = (v[..., 0] + MAX_SPEED) * (2 * MAX_SPEED + 1) + (v[..., 1] + MAX_SPEED)
    k = (2 * MAX_SPEED + 1) ** 2
    joint = np.zeros((k, k), dtype=np.int64)
    np.add.at(joint, (code[:, :-1].ravel(), code[:, 1:].ravel()), 1)

    n_trans = changed.size
    p_emp = float(changed.sum()) / n_trans
    out = dict(
        d=d,
        p_change=ds.p_change,
        p_smooth=ds.smooth_probability,
        # configured gap. The symmetric kernel HOLDS on a proposal that leaves
        # the grid, so the realised rate below is lower than p_change and the
        # realised gap correspondingly longer -- that is expected, not a bug.
        mean_gap=(1.0 / ds.p_change) if ds.p_change > 0 else math.inf,
        realised_rate=p_emp,
        realised_gap=(1.0 / p_emp) if p_emp > 0 else math.inf,
        entropy=_entropy_from_joint(joint),
        mean_speed=float(speed.mean()),
        net_disp=float(net.mean()),
        switches=float(switches.mean()),
        mean_age=float(ages.mean()),
        mean_dv=float(dv[changed].mean()) if changed.any() else 0.0,
        min_segment=ds.min_segment,
        max_segment=ds.max_segment,
    )
    _CACHE[(d, n_traj)] = out
    return out


def _all():
    return [measure(d) for d in D_GRID]


def format_table(rows):
    out = ["|   d  | p_change | H bits | mean|v| | net disp | switches | bnd age | E|dv| |",
           "|------|----------|--------|---------|----------|----------|---------|-------|"]
    for r in rows:
        out.append(f"| {r['d']:.2f} | {r['p_change']:8.3f} | {r['entropy']:6.3f} |"
                   f" {r['mean_speed']:7.3f} | {r['net_disp']:8.2f} |"
                   f" {r['switches']:8.2f} | {r['mean_age']:7.2f} | {r['mean_dv']:5.2f} |")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# tests
# ---------------------------------------------------------------------------
def test_legacy_kernel_is_unchanged():
    """The default stream must reproduce every existing fixed benchmark."""
    import hashlib

    cases = {
        "piecewise_smooth08":  dict(motion_mode="piecewise", transition_mode="smooth",
                                    min_segment=3, max_segment=6, smooth_probability=0.8),
        "stochastic_smooth08": dict(motion_mode="stochastic", transition_mode="smooth",
                                    p_change=0.25, smooth_probability=0.8),
        "stochastic_smooth10": dict(motion_mode="stochastic", transition_mode="smooth",
                                    p_change=0.5, smooth_probability=1.0),
    }
    for name, kw in cases.items():
        ds = TDMovingMNISTDataset(
            root=DATA_ROOT, train=False, seq_len=SEQ_LEN, num_digits=NUM_DIGITS,
            image_size=36, max_speed=MAX_SPEED, freeze_after=FREEZE, download=False,
            random=False, seed=1234, return_motion=True, **kw)
        assert ds.neighbor_kernel == "legacy", "the default kernel must stay legacy"
        ds.reset_rng()
        h = hashlib.sha256()
        for _ in range(300):
            h.update(ds._generate_motion_trajectory().numpy().astype(np.int16).tobytes())
        assert h.hexdigest() == LEGACY_TRAJECTORY_SHA256[name], (
            f"{name}: the legacy trajectory stream changed")


def test_speed_is_not_confounded_with_difficulty():
    """The whole point of the symmetric kernel: mean |v| flat across the sweep."""
    rows = _all()
    for r in rows:
        assert math.isclose(r["mean_speed"], UNIFORM_MEAN_SPEED, rel_tol=0.01), (
            f"d={r['d']}: mean |v| {r['mean_speed']:.3f} drifted from the uniform-grid "
            f"value {UNIFORM_MEAN_SPEED}")


def test_jump_size_is_not_swept():
    """E|dv| is a separate axis and must be constant for every d that switches."""
    vals = [r["mean_dv"] for r in _all() if r["d"] > 0]
    assert max(vals) - min(vals) < 0.05 * np.mean(vals), f"E|dv| drifted: {vals}"


def test_anchor_points():
    zero = measure(0.0)
    assert zero["p_change"] == 0.0
    assert zero["entropy"] == 0.0
    assert zero["switches"] == 0.0

    train = measure(0.5)
    assert math.isclose(train["p_change"], 1 / 4.5, rel_tol=1e-3)
    assert math.isclose(train["p_smooth"], 0.80, rel_tol=1e-3)
    assert math.isclose(train["mean_gap"], 4.5, rel_tol=0.10)
    assert (train["min_segment"], train["max_segment"]) == (3, 6)

    top = measure(1.0)
    assert top["p_change"] == 1.0
    # deliberately NOT the maximum-entropy process: holding smooth_probability at
    # 0.80 trades peak entropy for coherent travel
    assert top["entropy"] < math.log2(23)


def test_monotonicity():
    rows = _all()
    for key in ("entropy", "switches"):
        vals = [r[key] for r in rows]
        assert all(a < b for a, b in zip(vals, vals[1:])), f"{key} not increasing: {vals}"
    for key in ("net_disp", "mean_age"):
        vals = [r[key] for r in rows]
        assert all(a > b for a, b in zip(vals, vals[1:])), f"{key} not decreasing: {vals}"


def test_regression_targets():
    for r in _all():
        exp = EXPECTED[round(r["d"], 2)]
        for name, e in zip(FIELDS, exp):
            g = r[name]
            if e == 0.0:
                assert abs(g) < 1e-9, f"d={r['d']} {name}: {g} != 0"
            else:
                assert math.isclose(g, e, rel_tol=0.05), f"d={r['d']} {name}: {g} vs {e}"


def test_max_speed_is_off_the_difficulty_axis():
    ref = _dataset(0.0)
    for d in D_GRID:
        ds = _dataset(d)
        assert ds.max_speed == ref.max_speed
        assert ds.velocity_grid == ref.velocity_grid


def test_apply_difficulty_does_not_consume_rng():
    ds = _dataset(0.0)
    ds.reset_rng()
    before = ds.rng.get_state()
    ds._apply_difficulty(0.73)
    after = ds.rng.get_state()
    assert before[0] == after[0]
    assert np.array_equal(before[1], after[1])
    assert before[2:] == after[2:]


def test_forced_mode_warns_only_on_conflict():
    import warnings

    def build(**kw):
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            TDMovingMNISTDataset(
                root=DATA_ROOT, train=False, seq_len=SEQ_LEN, num_digits=NUM_DIGITS,
                image_size=36, max_speed=MAX_SPEED, download=False, random=False,
                seed=SEED, **kw)
        return [w for w in caught if issubclass(w.category, UserWarning)]

    assert not build(motion_difficulty=0.5)
    assert not build(motion_mode="accelerate")
    for kw in (dict(motion_difficulty=0.5, motion_mode="accelerate"),
               dict(motion_difficulty=0.5, transition_mode="uniform")):
        got = build(**kw)
        assert got, f"expected a UserWarning for {kw}"
        assert "motion_mode" in str(got[0].message)

    ds = _dataset(0.5)
    assert ds.motion_mode == "stochastic"
    assert ds.transition_mode == "smooth"
    assert ds.smooth_probability == 0.80


if __name__ == "__main__":
    print(f"n = {N_TRAJ} trajectories per d, kernel = {KERNEL}\n")
    rows = _all()
    print(format_table(rows))
    print("\nconfigured vs realised switching rate (symmetric holds on an "
          "off-grid proposal):")
    for r in rows:
        print(f"  d={r['d']:.2f}  p_change={r['p_change']:.3f}  "
              f"realised={r['realised_rate']:.3f}  "
              f"gap {r['mean_gap']:>6.2f} -> {r['realised_gap']:>6.2f}")
    print()
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            fn()
            print(f"  {name} ok")
